const fs = require('fs');
const path = require('path');

const filePath = './telegram-types.ts';
let content = fs.readFileSync(filePath, 'utf8');

// Fix interfaces that extend primitive types
content = content.replace(/export interface SendChatActionResponse extends boolean \{\}/g, 'export type SendChatActionResponse = boolean;');
content = content.replace(/export interface BanChatMemberResponse extends boolean \{\}/g, 'export type BanChatMemberResponse = boolean;');
content = content.replace(/export interface UnbanChatMemberResponse extends boolean \{\}/g, 'export type UnbanChatMemberResponse = boolean;');
content = content.replace(/export interface RestrictChatMemberResponse extends boolean \{\}/g, 'export type RestrictChatMemberResponse = boolean;');
content = content.replace(/export interface PromoteChatMemberResponse extends boolean \{\}/g, 'export type PromoteChatMemberResponse = boolean;');
content = content.replace(/export interface SetChatAdministratorCustomTitleResponse extends boolean \{\}/g, 'export type SetChatAdministratorCustomTitleResponse = boolean;');
content = content.replace(/export interface BanChatSenderChatResponse extends boolean \{\}/g, 'export type BanChatSenderChatResponse = boolean;');
content = content.replace(/export interface UnbanChatSenderChatResponse extends boolean \{\}/g, 'export type UnbanChatSenderChatResponse = boolean;');
content = content.replace(/export interface SetChatPermissionsResponse extends boolean \{\}/g, 'export type SetChatPermissionsResponse = boolean;');
content = content.replace(/export interface ExportChatInviteLinkResponse extends string \{\}/g, 'export type ExportChatInviteLinkResponse = string;');
content = content.replace(/export interface ApproveChatJoinRequestResponse extends boolean \{\}/g, 'export type ApproveChatJoinRequestResponse = boolean;');
content = content.replace(/export interface DeclineChatJoinRequestResponse extends boolean \{\}/g, 'export type DeclineChatJoinRequestResponse = boolean;');
content = content.replace(/export interface SetChatPhotoResponse extends boolean \{\}/g, 'export type SetChatPhotoResponse = boolean;');
content = content.replace(/export interface DeleteChatPhotoResponse extends boolean \{\}/g, 'export type DeleteChatPhotoResponse = boolean;');
content = content.replace(/export interface SetChatTitleResponse extends boolean \{\}/g, 'export type SetChatTitleResponse = boolean;');
content = content.replace(/export interface SetChatDescriptionResponse extends boolean \{\}/g, 'export type SetChatDescriptionResponse = boolean;');
content = content.replace(/export interface PinChatMessageResponse extends boolean \{\}/g, 'export type PinChatMessageResponse = boolean;');
content = content.replace(/export interface UnpinChatMessageResponse extends boolean \{\}/g, 'export type UnpinChatMessageResponse = boolean;');
content = content.replace(/export interface UnpinAllChatMessagesResponse extends boolean \{\}/g, 'export type UnpinAllChatMessagesResponse = boolean;');
content = content.replace(/export interface LeaveChatResponse extends boolean \{\}/g, 'export type LeaveChatResponse = boolean;');
content = content.replace(/export interface GetChatMemberCountResponse extends number \{\}/g, 'export type GetChatMemberCountResponse = number;');
content = content.replace(/export interface SetChatStickerSetResponse extends boolean \{\}/g, 'export type SetChatStickerSetResponse = boolean;');
content = content.replace(/export interface DeleteChatStickerSetResponse extends boolean \{\}/g, 'export type DeleteChatStickerSetResponse = boolean;');
content = content.replace(/export interface EditForumTopicResponse extends boolean \{\}/g, 'export type EditForumTopicResponse = boolean;');
content = content.replace(/export interface CloseForumTopicResponse extends boolean \{\}/g, 'export type CloseForumTopicResponse = boolean;');
content = content.replace(/export interface ReopenForumTopicResponse extends boolean \{\}/g, 'export type ReopenForumTopicResponse = boolean;');
content = content.replace(/export interface DeleteForumTopicResponse extends boolean \{\}/g, 'export type DeleteForumTopicResponse = boolean;');
content = content.replace(/export interface UnpinAllForumTopicMessagesResponse extends boolean \{\}/g, 'export type UnpinAllForumTopicMessagesResponse = boolean;');
content = content.replace(/export interface EditGeneralForumTopicResponse extends boolean \{\}/g, 'export type EditGeneralForumTopicResponse = boolean;');
content = content.replace(/export interface CloseGeneralForumTopicResponse extends boolean \{\}/g, 'export type CloseGeneralForumTopicResponse = boolean;');
content = content.replace(/export interface ReopenGeneralForumTopicResponse extends boolean \{\}/g, 'export type ReopenGeneralForumTopicResponse = boolean;');
content = content.replace(/export interface HideGeneralForumTopicResponse extends boolean \{\}/g, 'export type HideGeneralForumTopicResponse = boolean;');
content = content.replace(/export interface UnhideGeneralForumTopicResponse extends boolean \{\}/g, 'export type UnhideGeneralForumTopicResponse = boolean;');
content = content.replace(/export interface AnswerCallbackQueryResponse extends boolean \{\}/g, 'export type AnswerCallbackQueryResponse = boolean;');
content = content.replace(/export interface SetMyCommandsResponse extends boolean \{\}/g, 'export type SetMyCommandsResponse = boolean;');
content = content.replace(/export interface DeleteMyCommandsResponse extends boolean \{\}/g, 'export type DeleteMyCommandsResponse = boolean;');
content = content.replace(/export interface SetMyNameResponse extends boolean \{\}/g, 'export type SetMyNameResponse = boolean;');
content = content.replace(/export interface SetMyDescriptionResponse extends boolean \{\}/g, 'export type SetMyDescriptionResponse = boolean;');
content = content.replace(/export interface SetMyShortDescriptionResponse extends boolean \{\}/g, 'export type SetMyShortDescriptionResponse = boolean;');
content = content.replace(/export interface SetChatMenuButtonResponse extends boolean \{\}/g, 'export type SetChatMenuButtonResponse = boolean;');
content = content.replace(/export interface SetMyDefaultAdministratorRightsResponse extends boolean \{\}/g, 'export type SetMyDefaultAdministratorRightsResponse = boolean;');
content = content.replace(/export interface DeleteMessageResponse extends boolean \{\}/g, 'export type DeleteMessageResponse = boolean;');
content = content.replace(/export interface DeleteMessagesResponse extends boolean \{\}/g, 'export type DeleteMessagesResponse = boolean;');
content = content.replace(/export interface CreateNewStickerSetResponse extends boolean \{\}/g, 'export type CreateNewStickerSetResponse = boolean;');
content = content.replace(/export interface AddStickerToSetResponse extends boolean \{\}/g, 'export type AddStickerToSetResponse = boolean;');
content = content.replace(/export interface SetStickerPositionInSetResponse extends boolean \{\}/g, 'export type SetStickerPositionInSetResponse = boolean;');
content = content.replace(/export interface DeleteStickerFromSetResponse extends boolean \{\}/g, 'export type DeleteStickerFromSetResponse = boolean;');
content = content.replace(/export interface SetStickerEmojiListResponse extends boolean \{\}/g, 'export type SetStickerEmojiListResponse = boolean;');
content = content.replace(/export interface SetStickerKeywordsResponse extends boolean \{\}/g, 'export type SetStickerKeywordsResponse = boolean;');
content = content.replace(/export interface SetStickerMaskPositionResponse extends boolean \{\}/g, 'export type SetStickerMaskPositionResponse = boolean;');
content = content.replace(/export interface SetStickerSetTitleResponse extends boolean \{\}/g, 'export type SetStickerSetTitleResponse = boolean;');
content = content.replace(/export interface SetStickerSetThumbnailResponse extends boolean \{\}/g, 'export type SetStickerSetThumbnailResponse = boolean;');
content = content.replace(/export interface SetCustomEmojiStickerSetThumbnailResponse extends boolean \{\}/g, 'export type SetCustomEmojiStickerSetThumbnailResponse = boolean;');
content = content.replace(/export interface DeleteStickerSetResponse extends boolean \{\}/g, 'export type DeleteStickerSetResponse = boolean;');
content = content.replace(/export interface AnswerInlineQueryResponse extends boolean \{\}/g, 'export type AnswerInlineQueryResponse = boolean;');
content = content.replace(/export interface CreateInvoiceLinkResponse extends string \{\}/g, 'export type CreateInvoiceLinkResponse = string;');
content = content.replace(/export interface AnswerShippingQueryResponse extends boolean \{\}/g, 'export type AnswerShippingQueryResponse = boolean;');
content = content.replace(/export interface AnswerPreCheckoutQueryResponse extends boolean \{\}/g, 'export type AnswerPreCheckoutQueryResponse = boolean;');
content = content.replace(/export interface SetPassportDataErrorsResponse extends boolean \{\}/g, 'export type SetPassportDataErrorsResponse = boolean;');
content = content.replace(/export interface SetWebhookResponse extends boolean \{\}/g, 'export type SetWebhookResponse = boolean;');
content = content.replace(/export interface DeleteWebhookResponse extends boolean \{\}/g, 'export type DeleteWebhookResponse = boolean;');

fs.writeFileSync(filePath, content);
console.log('Fixed all interface extends primitive type issues');